name: workflow test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: setup ubuntu
    runs-on: ubuntu-latest

    steps:
      - name: setup actions
        uses: actions/checkout@v3

      - name: check run
        run: echo "Testing Workflow"

